### ISSUE TITLE
Separar en partes el ejercicio de Variable anónima

### ISSUE THREAD

**Issue by flbulgarelli** [pdep-utn/mumuki-guia-funcional-funciones-partidas-pattern-matching-tuplas#3]
Está un poquito largo. Capaz se podría partir en dos.

**Comment by gcrespi** [comment]
¿Estas seguro que te referís al de Variable anónima? hay otros ejercicios más largos.

**Comment by flbulgarelli** [comment]
Si, fue un poco exagerado. Ignorá esto
