### ISSUE TITLE
Eliminar el disclaimer en el ejercicio de Variable Anonima

### ISSUE THREAD

**Issue by flbulgarelli** [pdep-utn/mumuki-guia-funcional-funciones-partidas-pattern-matching-tuplas#4]
Aunque aun el runner de haskell no pueda evaluar la presencia de una variable anonima, eliminar el disclaimer del ejercicio. Cuando esté soportado, será efectivamente evaluado. 

Además, escribir de todas formas la expectativa. Las expectativas que el runner no sepa procesar serán ignoradas.

**Comment by gcrespi** [comment]
Closed by ec8ec9d37bc2a2c91cba92c43a785580376c245b
